MED_SCHOOL_TIERS = {
    "Tier_1": [
        # Top 30 (Highly Selective Research Focus)
        "Harvard Medical School",
        "Johns Hopkins University School of Medicine",
        "Perelman School of Medicine at the University of Pennsylvania",
        "NYU Grossman School of Medicine",
        "Stanford University School of Medicine",
        "Columbia University Vagelos College of Physicians and Surgeons",
        "Duke University School of Medicine",
        "Mayo Clinic Alix School of Medicine",
        "University of California—San Francisco (UCSF)",
        "Washington University in St. Louis School of Medicine",
        "Yale School of Medicine",
        "Weill Cornell Medicine",
        "University of Chicago Pritzker School of Medicine",
        "University of Michigan Medical School",
        "Northwestern University Feinberg School of Medicine",
        "University of Pittsburgh School of Medicine",
        "Vanderbilt University School of Medicine",
        "Icahn School of Medicine at Mount Sinai",
        "University of California—Los Angeles (Geffen)",
        "University of Texas Southwestern Medical School",
        "University of Washington School of Medicine",
        "Emory University School of Medicine",
        "University of California—San Diego (UCSD)",
        "Case Western Reserve University School of Medicine",
        "Baylor College of Medicine",
        "University of North Carolina—Chapel Hill",
        "University of Southern California Keck School of Medicine",
        "Brown University Alpert Medical School",
        "Boston University School of Medicine",
        "Dartmouth College Geisel School of Medicine",
    ],
    "Tier_2": [  # Top 31-60 (Strong Research and Prominent Public Schools)
        "University of Virginia School of Medicine",
        "Ohio State University College of Medicine",
        "University of Wisconsin School of Medicine and Public Health",
        "Albert Einstein College of Medicine",
        "University of Colorado School of Medicine",
        "University of Rochester School of Medicine and Dentistry",
        "Tufts University School of Medicine",
        "Georgetown University School of Medicine",
        "Hofstra/Northwell Zucker School of Medicine",
        "University of Florida College of Medicine",
        "University of Miami Leonard M. Miller School of Medicine",
        "University of Maryland School of Medicine",
        "University of Iowa Carver College of Medicine",
        "Stony Brook University Renaissance School of Medicine",
        "Rutgers Robert Wood Johnson Medical School",
        "University of Massachusetts Chan Medical School",
        "Wake Forest University School of Medicine",
        "University of Cincinnati College of Medicine",
        "University of California—Irvine School of Medicine",
        "Oregon Health & Science University",
        "University of Alabama—Birmingham (UAB)",
        "Medical College of Wisconsin",
        "University of Texas—Austin Dell Medical School",
        "Temple University Lewis Katz School of Medicine",
        "Thomas Jefferson University (Kimmel)",
        "University of Minnesota Medical School", "Rush Medical College",
        "Virginia Commonwealth University",
        "University of Texas Health Science Center—San Antonio",
        "Drexel University College of Medicine"
    ],
    "Tier_3": [  # Top 61-100 (Competitive and Mission-Focused Schools)
        "University of California—Davis School of Medicine",
        "Loma Linda University School of Medicine",
        "Texas A&M College of Medicine",
        "University of Illinois—Chicago (UIC)",
        "University of Nebraska Medical Center",
        "Penn State College of Medicine",
        "Saint Louis University School of Medicine",
        "Medical University of South Carolina (MUSC)",
        "University of Arizona College of Medicine—Tucson",
        "University of Hawaii—Manoa (JABSOM)",
        "Rutgers New Jersey Medical School",
        "University of Arkansas for Medical Sciences",
        "Indiana University School of Medicine",
        "Tulane University School of Medicine",
        "University of South Florida (USF Morsani)",
        "University of Buffalo Jacobs School of Medicine",
        "University of Oklahoma College of Medicine",
        "West Virginia University School of Medicine",
        "Michigan State University College of Human Medicine",
        "Florida State University College of Medicine",
        "University of Kansas School of Medicine",
        "Loyola University Chicago Stritch School of Medicine",
        "Albany Medical College", "Geisinger Commonwealth School of Medicine",
        "University of Missouri—Columbia School of Medicine",
        "Creighton University School of Medicine",
        "Rosalind Franklin University of Medicine and Science",
        "Medical College of Georgia at Augusta University",
        "University of Kentucky College of Medicine",
        "University of Louisville School of Medicine"
    ]
}
