name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to GCP
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Docker for Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker gcr.io --quiet

    # Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/smarterdoc-backend .

    # Push Docker image
    - name: Push Docker Image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/smarterdoc-backend

    # Deploy to Cloud Run with better configuration
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy smarterdoc-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/smarterdoc-backend \
          --platform managed \
          --region ${{ secrets.REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --timeout 300s \
          --concurrency 80 \
          --min-instances 0 \
          --max-instances 3