name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build & Push Backend Image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/smarterdoc-backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy smarterdoc-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/smarterdoc-backend \
          --platform managed \
          --region ${{ secrets.REGION }} \
          --allow-unauthenticated \
          --port 8080
